#!/bin/bash
curl --include \
	--header "Content-Type: application/json" \
	--header "Authorization: Basic Tkw6d2JTd0ZVNnRZMWM=" \
	--request POST \
	--data '{
"competition": "line",
"arena": "A", 
"round": "2", 
"teamname": "pi++", 
"time": {     
"timeRun": 57.82108,
"timestampRunStart": 1554854400,
"timestampRunEnd": 1558665000
},
"scoring": {  
"teamStarted": true
},
"comments": "",
"confirmedByTeamCaptain": true,
"complaints": ""
	}
	' \
	http://localhost:5000/api/v1/submit_run
