#!/bin/bash
curl --include \
    --header "Content-Type: application/json" \
    --header "Authorization: Basic dGVzdDp0ZXN0" \
    --request POST \
    --data '{
    "competition": "2020-berlin-line",
    "teamname": "pi++", 
    "round": 4, 
    "arena": "D", 
    "time_duration": 57,
    "time_start": 1554854400,
    "time_end": 1558665000,
    "scoring": {  
        "teamStarted": true
    },
    "comments": "",
    "confirmed": true,
    "complaints": ""
}
' \
    http://localhost:5000/api/v1/submit_run
